server:
  port: 8080
  
spring:
  application:
    name: msvc-gateway
  cloud:
    discovery:
      locator:
        enabled: true
      routes:
      - id: paciente
      uri: http://localhost:8090
      predicates:
        - Path=/api/v1/pacientes/**